### ISSUE TITLE
Action not allowed

### ISSUE THREAD

**Issue by Dektor** [Slimakoi/Amino.py#1]
_I wrote a bot that it have to connect to other accounts, but it works for a few minutes a day! then it gives the error_ "elif api_code == 110: raise ActionNotAllowed (data)
amino.lib.util.exceptions.ActionNotAllowed: {'api: message': 'Action not allowed.', 'api: timestamp': '2020-11-07T10: 20: 01Z', 'api: statuscode': 110, 'api: duration': '0.029s'} "_and this is the end and so every time. How can I fix this?_

**Comment by Slimakoi** [comment]
Hello Dektor.
I've seen many people have the same issue you're having and the only way I found a fix for it is using a Proxy or VPN.

Amino.py has an inbuilt method to implement a Proxy.
```python
proxy = {"http": "ip:port", "https": "ip:port"}
client = amino.Client(proxy=proxy)
```
> Small Note: The Proxy function is only available starting on version 1.2.3 of Amino.py. Which I'll push soon.

Hopefully this fixes your issue. Have a great day!

**Comment by Dektor** [comment]
> Hello Dektor.
> I've seen many people have the same issue you're having and the only way I found a fix for it is using a Proxy or VPN.
> 
> Amino.py has an inbuilt method to implement a Proxy.
> 
> ```python
> proxy = {"http": "ip:port", "https": "ip:port"}
> client = amino.Client(proxy=proxy)
> ```
> 
> > Small Note: The Proxy function is only available starting on version 1.2.3 of Amino.py. Which I'll push soon.
> 
> Hopefully this fixes your issue. Have a great day!

Ok, I'll wait for the new lib version to be released. Thanks for your feedback, have a nice day too!

**Comment by Dektor** [comment]
I tried a new patch to fix this 'ActionNotAllowed' error. I could not connect the proxies in the code and just connected them to my computer, but I only had a new problem: 'Please check your account before logging into the system on a new device.' Is there any function in the library for this solution?

**Comment by Slimakoi** [comment]
You can find list of proxies online, also to fix that issue, first you'll need to send a verification to your email
```python
client.request_verify_code(email="email here")
```
Then after you get it, complete the verification with this code
```python
client.verify(email="email here", code="code here")
```

**Comment by Dektor** [comment]
Yes, I found the list of proxy and connected it as you said, 

proxy = {"http": "176.120.63.35:1080"}
client = amino.Client(proxies=proxy)

but in all cases it either issued 'ActionNotAllowed' (most likely without connecting a proxy) or gave an error related to login
