### ISSUE TITLE
Error when defining subclient, "amino.lib.util.exceptions.UnsupportedService"

### ISSUE THREAD

**Issue by GrJT** [Slimakoi/Amino.py#12]
This error is triggered when i define a subclient:
`amino.lib.util.exceptions.UnsupportedService: {'api:message': 'Unsupported service. Your client may be out of date. Please update it to the latest version.', 'api:timestamp': '2021-01-25T17:59:50Z', 'api:statuscode': 100, 'api:duration': '0.000s'}`

This is my code (private stuff censored)
```
import amino

client = amino.Client()
client.login(email="email" , password="pass")

sub_client = amino.SubClient(comId='communityid', profile=client.profile)

sub_client.post_blog(title="test",content="this is a test blog")
```
I copied this code from another issue (https://github.com/Slimakoi/Amino.py/issues/5) because there's no documentation, and i'll learn through reading the module's classes. I created an Amino account and joined it to the community i'm trying to make a post. The community ID is correct, and i installed amino.py some minutes ago, so it isn't outdated.

Is there any way to fix this? Am i missing something?

**Comment by Slimakoi** [comment]
What did you put on `comId='communityid'`?

**Comment by GrJT** [comment]
> What did you put on `comId='communityid'`?
I put the community ID, the one that appears in the invite link, or in the Amino Manager. It is a string.

**Comment by StealthEliteV1** [comment]
You used `comId="0000"` incorrectly, the community ID is supposed to be an integer, not a string

You can get the community ID by using the following code:

id = client.get_from_code("EXAMPLE").objectId
print(id)

Replace "EXAMPLE" with a link to the Amino (https://aminoapps.com/p/EXAMPLE)

This will print out the correct community ID, use that and you should be good to go

**Comment by Slimakoi** [comment]
Change the `comId` to `aminoId` if youre using an amino id. Example below
```python
sub_client = amino.SubClient(aminoId='anime', profile=client.profile)
```

**Comment by GrJT** [comment]
Thank you for your help. Sorry, i should have done some research on it, your two solutions are really helpful, thank you.
Using the `aminoId` worked, but about the `id = client.get_from_code("EXAMPLE").objectId` solution, how can i get a "https://aminoapps.com/p/EXAMPLE" link? My community is private.

**Comment by Slimakoi** [comment]
It doesnt work for communities
