### ISSUE TITLE
Action not allowed, API code 110

### ISSUE THREAD

**Issue by SKISTE** [Slimakoi/Amino.py#19]
I cannot log in through the login module, writes Action not allowed and 110 API error, now how to use the library?
`def login():
	try:
		client.login(email=log, password=pasw)
	except Exception as e:
		print('Error: '+str(e)+'\n')
		sleep(2)
		login()`
**Error: {'api:duration': '0.112s', 'api:message': 'Action not allowed.', 'api:timestamp': '2021-03-01T14:21:59Z', 'api:statuscode': 110}**

**Comment by Slimakoi** [comment]
Change the device id on `device.json`
