### ISSUE TITLE
function send_coins

### ISSUE THREAD

**Issue by Dektor** [Slimakoi/Amino.py#2]
_The function "send_coins" stopped working in the new version._ 

**Here is my code**
```
	coins = client.get_wallet_info().totalCoinsFloat
	totalCoins=totalCoins+float(coins)
	sub_client.send_coins(coins=coins, blogId=' my blog id ', transactionId=' my blog id ')
```
**Here is the result**

> amino.lib.util.exceptions.CannotSendCoins: {'api:message': 'Sorry, you can not give props at this time.', 'api:timestamp': '2020-11-10T21:15:22Z', 'api:statuscode': 4501, 'api:duration': '0.027s'}

**Comment by wzc-Seer** [comment]
Hi! 
This can be fixed by removing the param `transactionId` if this does not work then please let me know.

**Comment by Dektor** [comment]
> Hi!
> This can be fixed by removing the param `transactionId` if this does not work then please let me know.

No without this argument he can't convert

**Comment by wzc-Seer** [comment]
Can you send the code you used. (the entire file) thanks!

**Comment by Slimakoi** [comment]
Hello I fixed the `send_coins` command, you shall update the library and try running your code. Thanks

**Comment by Dektor** [comment]
[coin_farm.zip](https://github.com/Slimakoi/Amino.py/files/5542515/coin_farm.zip)
My file for @wzc-Seer

**Comment by wzc-Seer** [comment]
Thanks for the file, i will look at it tommorow

**Comment by wzc-Seer** [comment]
Hi! 
I have debugged this issue and it should be fixed in the version that i will send to you, also make sure to update amino.py!

Any questions?
Make sure to ask me!
[solution.zip](https://github.com/Slimakoi/Amino.py/files/5547418/solution.zip)
