### ISSUE TITLE
Why generated device info is wrong?

### ISSUE THREAD

**Issue by darkwar123** [Slimakoi/Amino.py#21]
Why I can't login with device info generated with generate_device_info function?

**Comment by Slimakoi** [comment]
Any errors?

**Comment by darkwar123** [comment]
> Any errors?

always "Action not allowed." when execute login()

**Comment by darkwar123** [comment]
In last closed issue you gave to user "S1N0D" deviceid where did you get it? With it ("01A5CBA843EFCE77C4EDB9A84F0BD69E6307C9F60EC298FC0458F474340D71DEC6B72DA2456DFF7737") I can login.

**Comment by Slimakoi** [comment]
Duplicate of #19 

I got it from an HTTP sniffer, change your device id.

**Comment by S1N0D** [comment]
What HTTP sniffer do you use?

**Comment by Slimakoi** [comment]
Charles Proxy
