### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by S1N0D** [Slimakoi/Amino.py#22]
Hello. Is there a command in your list of functions that allows you to click on the "get daily prize" button located in the wallet?

**Comment by Slimakoi** [comment]
You mean the lottery?

**Comment by S1N0D** [comment]
Not. I mean the ability to view ads in the wallet, which is given four times a day with an interval of 14.5 minutes.

**Comment by Slimakoi** [comment]
No that isn't possible with the library

**Comment by S1N0D** [comment]
Excuse me, is there a function that allows the bot to stay online all the time?

**Comment by Slimakoi** [comment]
https://slimakoi.github.io/Amino.py/amino.html#amino.sub_client.SubClient.activity_status

**Comment by S1N0D** [comment]
Many thanks.
