### ISSUE TITLE
client.socket -open/-close problem

### ISSUE THREAD

**Issue by JoshJson** [Slimakoi/Amino.py#24]
Hello.
In order to keep the program alive I'm using this piece of code in the end:
```
while True:
    time.sleep(300)
    client.socket.close()
    client.socket.open()
```

**Problem:** The bot is not being turned off, however after random periods of time the amount of responses is being multiplied progressively.
For example on !help command it's supposed to send a simple text message. After 10 minutes of work it sends the message twice. After 10-20 minutes the bot sends it three times and so on. 

**Question:** Is this a bug? Is there any way to get around it? Thank you in advacnce for any help.

**Comment by Slimakoi** [comment]
That is an issue from amino
