### ISSUE TITLE
Problem with post requests

### ISSUE THREAD

**Issue by madgagarin** [Slimakoi/Amino.py#3]
When requested (follow), the API returns an error: “Unsupported service. Your client may be out of date. Please update it to the latest version.'
I tried to change information about the device, but it doesn't help

**Comment by madgagarin** [comment]
Although the login works fine

**Comment by Slimakoi** [comment]
Make sure the follow command has a valid user id

**Comment by madgagarin** [comment]
I tried different user id. Including valid. The result is the same.

**Comment by madgagarin** [comment]
I have verified my mail and phone. But when checking the status (profile.activation, profile.verified), the answer is no. Maybe this is the problem?
