### ISSUE TITLE
Unsupported service

### ISSUE THREAD

**Issue by SKISTE** [Slimakoi/Amino.py#30]
` {'api:duration': '0.000s', 'api:message': 'Unsupported service. Your client may be out of date. Please update it to the latest version.', 'api:timestamp': '2021-03-22T23:18:50Z', 'api:statuscode': 100}`
How to fix this? Use eel

**Comment by Serakoi** [comment]
@SKISTE Can you send your code?

**Comment by SKISTE** [comment]
What is the code?

**Comment by Serakoi** [comment]
Well, the code that error occured in.

**Comment by SKISTE** [comment]
`import amino
import eel
print('Начало работы')
eel.init('web')
Typec = '100'
idcommunity=''
idchat=''
client = amino.Client()

# LOGIN
@eel.expose
def login(log, pasw, idcommunity, idchat):
	try:
		client.login(email=log, password=pasw)
	except Exception as e:
		print('Ошибка в логине')
		print(str(e))
		eel.error(str(e))
	try:
		idcommunity = amino.Client().get_from_code(idcommunity)
		idcommunity = idcommunity.json["extensions"]["community"]["ndcId"]
		idchat = amino.Client().get_from_code(idchat).objectId
		print(f'Id коммунити: {idcommunity}')
		print(f'Id чата: {idchat}')
		idis = 'Id community: '+str(idcommunity)+'\nChat id: '+str(idchat)
		eel.info(idis)
	except Exception as e:
		print('Ошибка в айди')
		print(str(e))
		eel.error(str(e))
	eel.pokraska(1)

@eel.expose
def send(mesg):
	client.send_message(message=mesg, chatId=idchat, messageType=Typec)
	#sub_client = amino.SubClient(comId=idcommunity, profile=client.profile)
	try:
		sub_client.send_message(message=mesg, chatId=idchat, messageType=Typec)
	except Exception as e:
		eel.error(str(e))
eel.start("index.html", size=(655, 500), position=(500, 400), port=(0))`
