### ISSUE TITLE
How to get device ID?

### ISSUE THREAD

**Issue by Skyere** [Slimakoi/Amino.py#33]

**Comment by Skyere** [comment]
When i try start my bot, i recieved ActionNotAllowed. As I see in the other issues I need change device id. Where I can get it?

**Comment by okok7711** [comment]
You can get a fresh device ID on the discord server or by visiting ndc://fragment/com.narvii.util.debug.DebugInfoFragment in the amino App.
When you have that, change the string in device.json

**Comment by Skyere** [comment]
Which discord server? Can you say?

**Comment by Slimakoi** [comment]
Join my discord server and on #bot-commands run the command `f!deviceid` to get a new device id
https://discord.gg/bnnCwzV8ST
