### ISSUE TITLE
register

### ISSUE THREAD

**Issue by Rey646** [Slimakoi/Amino.py#50]
How to use client.register, if verification code is not incoming on email?

**Comment by Slimakoi** [comment]
You need a code to register

**Comment by okok7711** [comment]
`client.request_verify_code(email)`
you can also use an empty string as verificationCode that will create an unverified account

**Comment by Rey646** [comment]
> You need a code to register

Okay, how can I get it?

**Comment by Rey646** [comment]
> `client.request_verify_code(email)`
> you can also use an empty string as verificationCode that will create an unverified account

3102, 'Incorrect verification code'

**Comment by Rey646** [comment]
Okay, i understood
