### ISSUE TITLE
TypeError: login() missing 1 required positional argument: 'password'

### ISSUE THREAD

**Issue by GameDevGabe** [Slimakoi/Amino.py#54]
The Client.login() function outputs an error stating that  the 'password' argument is missing. However, I included that argument as in the following code:

```
import amino
from amino import client

amino.Client.login('xxxxxxxxx@gmail.com', '12345678')
```

I've tried many different things, but they all kept giving me different errors. How can I login into my account using the API?

**Comment by okok7711** [comment]
You haven't initted the client yet. This is not how classes work.

Example for logging in:
```
import amino

client = amino.Client()

client.login("koiIsHot@gmail.com", "nicePass69")

#foo stuff
```

**Comment by GameDevGabe** [comment]
That's the first thing I tried. It didn't work.

**Comment by okok7711** [comment]
> That's the first thing I tried. It didn't work.

Any error then?

**Comment by GameDevGabe** [comment]
> > That's the first thing I tried. It didn't work.
> 
> Any error then?

Yes, I got the 'Action not allowed' error. But after I opened this issue, I found out about the device id and managed to solve the error. Thanks!
