### ISSUE TITLE
Unsupported service 

### ISSUE THREAD

**Issue by EnderDremurr** [Slimakoi/Amino.py#55]
UnsupportedService(data)
amino.lib.util.exceptions.UnsupportedService: {'api:duration': '0.000s', 'api:message': 'Unsupported service. Your client may be out of date. Please update it to the latest version.', 'api:timestamp': '2021-07-10T13:05:23Z', 'api:statuscode': 100}

**Comment by okok7711** [comment]
You most likely made a mistake in your code

**Comment by EnderDremurr** [comment]
> You most likely made a mistake in your code

import time, amino as Amino

Login = input("Email: ")
Password = input("Password: ")
print(f"""Login: {Login}. Password: {Password}""")

Account = Amino.Client()
Account.login(email=Login,password=Password)
Client = Amino.SubClient(comId="anime", profile=Account.profile)


def joinchat():
        chat = input("ChatId: ")
        try: Client.join_chat(chat)
        except: pass

def Flooder(Client):
        message = input("Message: ")
        chat = input("ChatId: ")
        try:    Client.send_message(message=Message, chatId=chat)
        except: pass

**Comment by okok7711** [comment]
most likely wrong chatId
also if this chat isn't global you should use SubClient instead of Client

**Comment by EnderDremurr** [comment]
> most likely wrong chatId
> also if this chat isn't global you should use SubClient instead of Client

what should be in devise.json?
